---
test-length: 10
test-interval: 30
server-port: 5201
grafana-address: 192.168.1.47
grafana-port: 2003
tsdb-download-prefix: bandwidth.download
tsdb-upload-prefix: bandwidth.upload
endpoint-name: iperf
iperf-servers:
  - 172.17.0.3: azure
